name: Build devcontainers

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: calavia-org/workflows-lib/.github/workflows/build-container.yml@main
    with:
      container-file: Dockerfile
      context: .
      repository: devcontainer-base